
from typing import List

from logging import INFO
from logging import basicConfig

import zlib

from pathlib import Path

from re import findall
from re import sub as regExSub

from difflib import unified_diff

from PIL import ImageGrab
from PIL.Image import Image

from pyautogui import moveTo
from pyautogui import click
from pyautogui import press
from pyautogui import typewrite

from pymsgbox import alert

from umldiagrammeruitests.ToolBarClicker import ToolBarClicker
from umldiagrammeruitests.locators.BaseLocator import Location
from umldiagrammeruitests.locators.ClassDialogLocator import ClassDialogLocator

#
# The following generated by Gemini 0.22.4 using gemini-2.5-pro
# (wah, I cheated)
# I removed the appropriate id strings from the UI tests generate.  That
# way I can compare the structures
#
ID_NAME_MATCH = '(?:id|ModelLink name)=["]([^"]*)["]'

EMPTY_ID:             str = ''

LEFT:                   str   = 'left'
DRAG_DURATION:          float = 0.5
TYPE_WRITE_INTERVAL:    float = 0.1
DOUBLE_CLICK_INTERVAL:  float = 0.2

LOC_TOOLBAR_Y: int = 65

LOC_CLASS_TOOL_BAR:         Location = Location(x=730, y=LOC_TOOLBAR_Y)

LOC_CLICK_SAVE_PROJECT:      Location = Location(x=395, y=LOC_TOOLBAR_Y)
LOC_CLICK_SAVE_AS_NAME:      Location = Location(x=1420, y=350)
LOC_CLICK_SAVE_BUTTON:       Location = Location(x=1740, y=755)

MOVE_TO_DELAY: float = 0.9

BACKSPACES_CLEAR_CLASS_NAME: int   = 15
PAUSE_AFTER_EACH_CALL:       float = 0.50

BEST_FORMAT:   str = '%(asctime)s.%(msecs)03d %(levelname)-5s %(name)-4s - %(message)s'
SIMPLE_FORMAT: str = '%(asctime)s.%(msecs)03d %(levelname)s %(module)s: %(message)s'
TEST_FORMAT:   str = '%(levelname)s: %(module)s: %(message)s'

#
# This is fragile; Has to agree with the UML Diagrammer project
DIAGRAMMER_IN_TEST_MODE: Path = Path('/tmp/UmlDiagrammer.txt')
DEFAULT_METHOD_NAME:     str  = 'MethodName'

def setupLogging():
    basicConfig(
        level=INFO,
        format=TEST_FORMAT
    )

def isAppRunning() -> bool:
    answer: bool = False

    if DIAGRAMMER_IN_TEST_MODE.exists() is True:
        answer = True

    return answer

def makeAppActive():
    # Make UML Diagrammer Active
    moveTo(350, 175, duration=MOVE_TO_DELAY)
    click()

def pullDownViewMenu():
    # Pull down view menu
    click(220, 20, button=LEFT)

def takeCompletionScreenShot(imagePath: Path):

    imagePath.unlink(missing_ok=True)

    left:   int = 18
    top:    int = 39
    right:  int = 1030
    bottom: int = 730

    bbox = (left, top, right, bottom)

    # Capture the specified region
    screenshot: Image = ImageGrab.grab(bbox)
    screenshot.save(imagePath, 'png')

def decompress(inputFileName: Path, outputFileName: Path):
    """
    Takes a zlib compressed file and turns it into a text file
    Args:
        inputFileName:   The compressed file
        outputFileName:  The decompressed text file

    """
    try:
        with open(inputFileName, "rb") as inputFile:
            # print(f'Inflating: {inputFileName}')
            compressedData: bytes = inputFile.read()

            # print(f'Bytes read: {len(compressedData)}')
            xmlBytes:  bytes = zlib.decompress(compressedData)  # has b '....' around it
            xmlString: str   = xmlBytes.decode()

            # print(f'Writing {len(xmlString)} bytes to {outputFileName}')
            with open(outputFileName, 'w') as outputFile:
                outputFile.write(xmlString)
    except (ValueError, Exception) as e:
        print(f'Error:  {e}')

def runComparison(xmlToFix: str, patternToMatch: str) -> str:
    """

    Args:
        xmlToFix:           The raw generated XML from a test
        patternToMatch:     The find regex pattern that let's us remove unique IDs and names

    Returns:  The 'sanitized' XML

    """
    matchList: List[str] = findall(patternToMatch, xmlToFix)

    correctedXml: str = xmlToFix
    for matchedIdStr in matchList:
        correctedXml = regExSub(pattern=matchedIdStr, repl=EMPTY_ID, string=correctedXml)

    return correctedXml

def wasTestSuccessful(projectFileName: Path, decompressedProjectFileName: Path, goldenXml: str) -> bool:
    """

    Args:
        projectFileName:                The fully qualified path to the generated test project
        decompressedProjectFileName:    Where we decompress the project to
        goldenXml:                      The expected Golden XML

    Returns:  True if the generated XML matches the expected aka Golden XML

    """

    answer: bool = True

    decompress(inputFileName=projectFileName, outputFileName=decompressedProjectFileName)

    generatedXmlFile: Path = Path(decompressedProjectFileName)
    generatedXml:     str  = generatedXmlFile.read_text()

    fixedXml = runComparison(xmlToFix=generatedXml, patternToMatch=ID_NAME_MATCH)
    if fixedXml != goldenXml:
        diff = unified_diff(
            goldenXml.splitlines(),
            fixedXml.splitlines(),
            fromfile='Golden',
            tofile='Generated'
        )
        print('\n'.join(list(diff)))
        answer = False

    return answer

def displayAppropriateDialog(status: bool):
    """
    We will either congratulate the tester or admonish him
    Args:
        status:   The test status

    """

    if status is True:
        title: str = 'Success'
        message: str = 'You are a great programmer'
    elif status is False:
        title = 'Failure'
        message = 'You have failed as a programmer.  Check the console output'
    else:
        assert False, 'Developer error'

    alert(text=message, title=title, button='OK')

def renameClass(newClassName: str, locator: ClassDialogLocator):

    textInputLocation: Location = locator.classNameTextInput
    click(x=textInputLocation.x, y=textInputLocation.y)

    press(keys='backspace', presses=BACKSPACES_CLEAR_CLASS_NAME)
    typewrite(newClassName)

def createClassPair(class1Location: Location, class2Location: Location, class1Name: str, class2Name: str):

    createUmlClass(classLocation=class1Location, className=class1Name)
    createUmlClass(classLocation=class2Location, className=class2Name)

def createUmlClass(classLocation: Location, className: str):

    classDialogLocator: ClassDialogLocator = ClassDialogLocator()

    toolBarClicker: ToolBarClicker = ToolBarClicker()
    toolBarClicker.clickNewClass()

    click(x=classLocation.x, y=classLocation.y)     # Place it !!

    renameClass(newClassName=className, locator=classDialogLocator)

    clickClassOkButton: Location = classDialogLocator.clickClassOkButton
    click(x=clickClassOkButton.x, y=clickClassOkButton.y)
