
from typing import Tuple

from logging import INFO
from logging import basicConfig

from pathlib import Path

from xml.etree.ElementTree import indent
from xml.etree.ElementTree import Element
from xml.etree.ElementTree import tostring
from xml.etree.ElementTree import fromstring

from PIL import ImageGrab
from PIL.Image import Image

from pyautogui import moveTo
from pyautogui import click

from pymsgbox import alert

from umldiagrammeruitests.locators.BaseLocator import Location

#
# The following generated by Gemini 0.22.4 using gemini-2.5-pro
# (wah, I cheated)
# I removed the appropriate id strings from the UI tests generate.  That
# way I can compare the structures
#
ID_NAME_MATCH: str = '(?:id|ModelLink name)=["]([^"]*)["]'

EMPTY_ID:             str = ''

LEFT:                   str   = 'left'
DRAG_DURATION:          float = 0.5
TYPE_WRITE_INTERVAL:    float = 0.1
DOUBLE_CLICK_INTERVAL:  float = 0.2

LOC_TOOLBAR_Y: int = 65

LOC_CLASS_TOOL_BAR:         Location = Location(x=730, y=LOC_TOOLBAR_Y)

LOC_CLICK_SAVE_PROJECT:      Location = Location(x=395, y=LOC_TOOLBAR_Y)
LOC_CLICK_SAVE_AS_NAME:      Location = Location(x=1420, y=350)
LOC_CLICK_SAVE_BUTTON:       Location = Location(x=1740, y=755)

MOVE_TO_DELAY: float = 0.9

BACKSPACES_CLEAR_CLASS_NAME: int   = 15
PAUSE_AFTER_EACH_CALL:       float = 0.50

BEST_FORMAT:   str = '%(asctime)s.%(msecs)03d %(levelname)-5s %(name)-4s - %(message)s'
SIMPLE_FORMAT: str = '%(asctime)s.%(msecs)03d %(levelname)s %(module)s: %(message)s'
TEST_FORMAT:   str = '%(levelname)s: %(module)s: %(message)s'

#
# This is fragile; Has to agree with the UML Diagrammer project
DIAGRAMMER_IN_TEST_MODE: Path = Path('/tmp/UmlDiagrammer.txt')
# This is fragile; Has to agree with the UML Shapes preferences
DEFAULT_METHOD_NAME:     str  = 'MethodName'

APPLE_SCRIPT_SEND_KEYSTROKES: str = 'tell application "System Events" to keystroke'

def setupLogging():
    basicConfig(
        level=INFO,
        format=TEST_FORMAT
    )

def makeAppActive():
    # Make UML Diagrammer Active
    moveTo(350, 175, duration=MOVE_TO_DELAY)
    click()

def pullDownViewMenu():
    # Pull down view menu
    click(220, 20, button=LEFT)

def takeCompletionScreenShot(imagePath: Path):

    imagePath.unlink(missing_ok=True)

    left:   int = 18
    top:    int = 39
    right:  int = 1030
    bottom: int = 730

    bbox: Tuple[int, int, int, int] = (left, top, right, bottom)

    # Capture the specified region
    screenshot: Image = ImageGrab.grab(bbox)
    screenshot.save(imagePath, 'png')

def displayAppropriateDialog(status: bool):
    """
    We will either congratulate the tester or admonish him
    Args:
        status:   The test status

    """

    title:   str
    message: str
    if status is True:
        title = 'Success'
        message = 'You are a great programmer'
    elif status is False:
        title = 'Failure'
        message = 'You have failed as a programmer.  Check the console output'
    else:
        assert False, 'Developer error'

    alert(text=message, title=title, button='OK')

def prettyFormatXML(rawXml: str) -> str:
    """
    Pretty format an XML string with indentation

    Args:
        rawXml: The unformatted XML string

    Returns: The indented XML string, or rawXml if parsing fails
    """

    prettyXml: str = rawXml
    try:
        xmlRoot: Element = fromstring(rawXml)
        indent(tree=xmlRoot, space='    ')
        prettyXml = tostring(element=xmlRoot, encoding='unicode')
    except Exception as e:
        print(f'Failed to pretty format XML: {e}')

    return prettyXml
