from typing import Iterator
from typing import List

from logging import Logger
from logging import getLogger

from pathlib import Path

from re import findall
from re import sub as regExSub

from difflib import unified_diff

from zlib import decompress

from click import clear
from click import secho
from click import ClickException

from pyautogui import click
from pyautogui import moveTo
from pyautogui import press
from pyautogui import typewrite

from pymsgbox import alert

from umldiagrammeruitests.verifiers.AbstractVerifier import AbstractVerifier

from umldiagrammeruitests.Common import BACKSPACES_CLEAR_CLASS_NAME
from umldiagrammeruitests.Common import MOVE_TO_DELAY
from umldiagrammeruitests.SaveAsProject import SaveAsProject

from umldiagrammeruitests.ToolBarClicker import ToolBarClicker

from umldiagrammeruitests.locators.BaseLocator import Location
from umldiagrammeruitests.locators.ClassDialogLocator import ClassDialogLocator
from umldiagrammeruitests.locators.UmlClassLocator import UmlClassLocator

DIAGRAMMER_IN_TEST_MODE: Path = Path('/tmp/UmlDiagrammer.txt')

#
# The following generated by Gemini 0.22.4 using gemini-2.5-pro
# (wah, I cheated)
# I removed the appropriate id strings from the UI tests generate.  That
# way I can compare the structures
#
ID_NAME_MATCH: str = '(?:id|ModelLink name)=["]([^"]*)["]'

EMPTY_ID: str = ''

class BaseVerifier(AbstractVerifier):
    def __init__(self):

        self.bLogger: Logger = getLogger(__name__)

        self._umlClassLocator:    UmlClassLocator    = UmlClassLocator()
        self._classDialogLocator: ClassDialogLocator = ClassDialogLocator()
        self._toolBarClicker:     ToolBarClicker     = ToolBarClicker()
        self._saveAsProject:      SaveAsProject      = SaveAsProject()

    def execute(self):

        if self._isUmlDiagrammerReady() is False:
            errorMessage: str = 'The diagrammer is not running'
            alert(text=errorMessage, title='Hey, bonehead', button='OK')
            raise ClickException(errorMessage)

    def _isUmlDiagrammerReady(self) -> bool:
        answer: bool = False

        if DIAGRAMMER_IN_TEST_MODE.exists() is True:
            answer = True

        return answer

    def _bringUmlDiagrammerToForeground(self):
        # Make UML Diagrammer Active
        moveTo(350, 175, duration=MOVE_TO_DELAY)
        click()

    def _createUmlClassPair(self, class1Location: Location, class2Location: Location, class1Name: str, class2Name: str):

        self._createUmlClass(classLocation=class1Location, className=class1Name)
        self._createUmlClass(classLocation=class2Location, className=class2Name)

    def _createUmlClass(self, classLocation: Location, className: str):

        self._toolBarClicker.clickNewClass()
        secho(f'Click to create {className}')
        click(x=classLocation.x, y=classLocation.y)     # Place it !!

        self._renameUmlClass(newClassName=className)

        clickClassOkButton: Location = self._classDialogLocator.clickClassOkButton
        moveTo(x=clickClassOkButton.x, y=clickClassOkButton.y, duration=0.5)
        click(x=clickClassOkButton.x, y=clickClassOkButton.y)

    def _renameUmlClass(self, newClassName: str):

        HACK_ADJUST_X: int = 5
        textInputLocation: Location = self._classDialogLocator.classNameTextInput
        click(x=textInputLocation.x + HACK_ADJUST_X, y=textInputLocation.y)

        press(keys='backspace', presses=BACKSPACES_CLEAR_CLASS_NAME)
        typewrite(newClassName)

    def _verifyTest(self, projectFileName: Path, decompressedProjectFileName: Path, goldenXml: str) -> bool:
        """
        Verifies the generated XML against the golden XML and displays the result dialog.

        Args:
            projectFileName:             The path to the generated test project
            decompressedProjectFileName: Where we decompress the project to
            goldenXml:                   The expected Golden XML

        Returns:
            True if the test succeeded, False otherwise
        """
        testSuccessful: bool = self._wasTestSuccessful(
            projectFileName=projectFileName,
            decompressedProjectFileName=decompressedProjectFileName,
            goldenXml=goldenXml
        )

        self._displayAppropriateDialog(status=testSuccessful)

        return testSuccessful

    def _wasTestSuccessful(self, projectFileName: Path, decompressedProjectFileName: Path, goldenXml: str) -> bool:
        """

        Args:
            projectFileName:                The fully qualified path to the generated test project
            decompressedProjectFileName:    Where we decompress the project to
            goldenXml:                      The expected Golden XML

        Returns:  True if the generated XML matches the expected aka Golden XML

        """

        answer: bool = True

        self._decompress(inputFileName=projectFileName, outputFileName=decompressedProjectFileName)

        generatedXmlFile: Path = Path(decompressedProjectFileName)
        generatedXml:     str  = generatedXmlFile.read_text()

        fixedXml: str = self._runComparison(xmlToFix=generatedXml, patternToMatch=ID_NAME_MATCH)
        if fixedXml != goldenXml:
            diff = unified_diff(
                goldenXml.splitlines(),
                fixedXml.splitlines(),
                fromfile='Golden',
                tofile='Generated'
            )
            self._prettyPrintDiffs(diff)
            answer = False

        return answer

    def _decompress(self, inputFileName: Path, outputFileName: Path):
        """
        Takes a zlib compressed file and turns it into a text file
        Args:
            inputFileName:   The compressed file
            outputFileName:  The decompressed text file

        """
        try:
            with open(inputFileName, 'rb') as inputFile:
                # print(f'Inflating: {inputFileName}')
                compressedData: bytes = inputFile.read()

                # print(f'Bytes read: {len(compressedData)}')
                xmlBytes:  bytes = decompress(compressedData)  # has b '....' around it
                xmlString: str   = xmlBytes.decode()

                # print(f'Writing {len(xmlString)} bytes to {outputFileName}')
                with open(outputFileName, 'w') as outputFile:
                    outputFile.write(xmlString)
        except (ValueError, Exception) as e:
            self.bLogger.error(f'Error:  {e}')

    def _runComparison(self, xmlToFix: str, patternToMatch: str) -> str:
        """

        Args:
            xmlToFix:           The raw generated XML from a test
            patternToMatch:     The find regex pattern that let's us remove unique IDs and names

        Returns:  The 'sanitized' XML

        """
        matchList: List[str] = findall(patternToMatch, xmlToFix)

        correctedXml: str = xmlToFix
        for matchedIdStr in matchList:
            correctedXml = regExSub(pattern=matchedIdStr, repl=EMPTY_ID, string=correctedXml)

        return correctedXml

    def _displayAppropriateDialog(self, status: bool):
        """
        We will either congratulate the tester or admonish him
        Args:
            status:   The test status

        """

        if status is True:
            title: str = 'Success'
            message: str = 'You are a great programmer'
        elif status is False:
            title = 'Failure'
            message = 'You have failed as a programmer.  Check the console output'
        else:
            assert False, 'Developer error'

        alert(text=message, title=title, button='OK')

    def _prettyPrintDiffs(self, diff: Iterator[str]):
        """
        I like my Gemini 3.7 flash generated code !!

        Args:
            diff:  The return value from a call to unified_diff

        """
        clear()
        secho('--- XML Differences (Golden vs Generated) ---', fg='yellow', bold=True)
        for diffLine in diff:
            if diffLine.startswith('+'):
                secho(diffLine, fg='green')
            elif diffLine.startswith('-'):
                secho(diffLine, fg='red')
            elif diffLine.startswith('@'):
                secho(diffLine, fg='cyan')
            else:
                secho(diffLine, fg='black')
